//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMANDE_CONGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMANDE_CONGE()
        {
            this.AVIS_DM = new HashSet<AVIS_DM>();
        }
    
        public decimal ID_DEMANDE { get; set; }
        public string MATRECULE { get; set; }
        public string PERIODE { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public string FICHIER_JUST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVIS_DM> AVIS_DM { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
