//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPLACEMENT
    {
        public int ID_DEPLACEMENT { get; set; }
        public string MATRECULE { get; set; }
        public string DATE_DEPART { get; set; }
        public string DATE_RETOUR { get; set; }
        public string DESTINATION { get; set; }
        public double FRAIS_DEP { get; set; }
        public string MOYENS_DEP { get; set; }
        public string Avis_dep { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
