//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public decimal ID_DOC { get; set; }
        public string LB_DOC { get; set; }
        public string FICH_DOC { get; set; }
        public string DESC_DOC { get; set; }
    }
}
