//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ABSENCEs = new HashSet<ABSENCE>();
            this.BULLETIN_DE_PAIE = new HashSet<BULLETIN_DE_PAIE>();
            this.DEMANDE_CONGE = new HashSet<DEMANDE_CONGE>();
            this.DEPARTs = new HashSet<DEPART>();
            this.DEPLACEMENTs = new HashSet<DEPLACEMENT>();
            this.PRIMEs = new HashSet<PRIME>();
            this.USERs = new HashSet<USER>();
        }
    
        public string MATRECULE { get; set; }
        public string CIN { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string SEXE { get; set; }
        public string DATE_NAIS { get; set; }
        public string SITUATION_FAM { get; set; }
        public Nullable<int> NB_ENFANT { get; set; }
        public string PHOTO { get; set; }
        public string DATE_DEBCONTRAT { get; set; }
        public string DATE_FINCONT { get; set; }
        public string SERVICE { get; set; }
        public string ADRESSE { get; set; }
        public string TEL { get; set; }
        public string EMAIL { get; set; }
        public string DATE_EMBAUCHE { get; set; }
        public Nullable<int> NB_JOURCONGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABSENCE> ABSENCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BULLETIN_DE_PAIE> BULLETIN_DE_PAIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMANDE_CONGE> DEMANDE_CONGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPART> DEPARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPLACEMENT> DEPLACEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIME> PRIMEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
    }
}
