//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_RHEntities1 : DbContext
    {
        public E_RHEntities1()
            : base("name=E_RHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABSENCE> ABSENCEs { get; set; }
        public virtual DbSet<AVIS_DM> AVIS_DM { get; set; }
        public virtual DbSet<BULLETIN_DE_PAIE> BULLETIN_DE_PAIE { get; set; }
        public virtual DbSet<DEMANDE_CONGE> DEMANDE_CONGE { get; set; }
        public virtual DbSet<DEPART> DEPARTs { get; set; }
        public virtual DbSet<DEPLACEMENT> DEPLACEMENTs { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENTs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<FORMATION> FORMATIONs { get; set; }
        public virtual DbSet<PRIME> PRIMEs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
