//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATION
    {
        public int REF_FORMATION { get; set; }
        public string LIB { get; set; }
        public string DATE_DEPUT { get; set; }
        public int NB_JOUR { get; set; }
        public int NB_PARTICIPE { get; set; }
        public string DESC_SUJET { get; set; }
        public string NOM_FORMATEUR { get; set; }
    }
}
