//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class USER
    {
        public int ID_USER { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string CATEG { get; set; }
        public string MATRECULE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
